linux64_ci:
  image: onelab/ubuntu20.04
  script:
    - mkdir build
    - cd build
    - export CXXFLAGS=-Werror
    - cmake ..
    - make -j 8
    - ctest -j 8 --output-on-failure
    - valgrind --leak-check=full --error-exitcode=1 ./gmsh ../tutorial/t5.geo -3

linux64_compatibility_ci:
  image: onelab/ubuntu20.04
  script:
    - mkdir build
    - cd build
    - cmake -DDEFAULT=0 ..
    - make -j 8
    - cmake -DENABLE_PARSER=1 ..
    - make -j 8
    - cmake -DENABLE_POST=1 ..
    - make -j 8
    - cmake -DENABLE_MESH=1 -DENABLE_BUILD_DYNAMIC=1 -DENABLE_PRIVATE_API=1 -DENABLE_EIGEN=0 -DENABLE_WRAP_PYTHON=1 -DENABLE_PETSC=1 ..
    - make -j 8
