name: MacOS
on: 
  push:
    branches: master
    # tags:
    #   - 'V*'
jobs:
  buildApp:
    name: library
    runs-on: macos-latest
    env:
      MACOS_CERTIFICATE: ${{ secrets.MACOS_CERTIFICATE }}
      MACOS_CERTIFICATE_PWD: ${{ secrets.MACOS_CERTIFICATE_PWD }}
      TMP_PWD: hydrothermalfoam
      APPLEDEVELOPERID_APP: ${{ secrets.APPLEDEVELOPERID_APP }}
      QT_DIR: /usr/local/Cellar/qt@5/5.15.2
    steps:
      # checkout source code
      - uses: actions/checkout@v2
      - name: install dependence
        run: |
          brew install opencascade
          brew install fltk
          brew install hdf5
          brew install qt5
          export LIBRARY_PATH=/usr/local/lib
      # debug workflow through ssh
      - name: install oh my zsh
        run: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
      - uses: actions/checkout@v2
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
      
      # build app
      - name: build app
        run: |
          mkdir -p gmsh/build
          cd gmsh/build
          cmake -DCMAKE_BUILD_TYPE=Release ..
          make 
          ${QT_DIR}/bin/macdeployqt gmsh.app -dmg

      - uses: actions/upload-artifact@v2
        with:
          name: gmsh.dmg
          path: gmsh/build/gmsh.dmg

